# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/bios_ram/bios_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bios_ram || ORIG_REF_NAME==bios_ram} -quiet] -quiet

# IP: new/rtl_up/Decoder_0/Decoder_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Decoder_0 || ORIG_REF_NAME==Decoder_0} -quiet] -quiet
