# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.cache/wt [current_project]
set_property parent.project_path C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/lily/Desktop/stu_workspace/lab1_io/lab1_io.srcs/sources_1/new/S86_ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/lily/Desktop/123/lab3_3.coe
read_verilog -library xil_defaultlib {
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/ACKgenerator.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/Digit.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/Muxdati.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/RAM_BIOS.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/S_8254.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/Switch.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/WRgenerator.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/divclk.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/key_latch.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/reset.v
  C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/S86_top.v
}
read_ip -quiet C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/bios_ram/bios_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/bios_ram/bios_ram_ooc.xdc]

read_ip -quiet C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/new/rtl_up/Decoder_0/Decoder_0.xci

read_ip -quiet C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/S86_0/S86_0.xci

read_ip -quiet C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll.xci
set_property used_in_implementation false [get_files -all c:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/lily/Desktop/123/lab3_8254/lab3_8254/lab3_8254.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top S86_top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef S86_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file S86_top_utilization_synth.rpt -pb S86_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
