# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll.xci
# IP: The module: 'pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll.xci
# IP: The module: 'pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EES-351-V1.1/project/lab3_8254/lab3_8254.srcs/sources_1/ip/pll/pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
