set_property IOSTANDARD LVCMOS33 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports button_rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100_]
set_property PACKAGE_PIN AB10 [get_ports {switch_[0]}]
set_property PACKAGE_PIN AA9 [get_ports {switch_[1]}]
set_property PACKAGE_PIN Y9 [get_ports {switch_[2]}]
set_property PACKAGE_PIN V8 [get_ports {switch_[3]}]
set_property PACKAGE_PIN A22 [get_ports {switch_[8]}]
set_property PACKAGE_PIN D22 [get_ports {switch_[9]}]
set_property PACKAGE_PIN C22 [get_ports {switch_[10]}]
set_property PACKAGE_PIN Y8 [get_ports {segs1[0]}]
set_property PACKAGE_PIN AA8 [get_ports {segs1[1]}]
set_property PACKAGE_PIN W7 [get_ports {segs1[2]}]
set_property PACKAGE_PIN Y5 [get_ports {segs1[3]}]
set_property PACKAGE_PIN W5 [get_ports {segs1[4]}]
set_property PACKAGE_PIN W8 [get_ports {segs1[5]}]
set_property PACKAGE_PIN AB6 [get_ports {segs1[6]}]
set_property PACKAGE_PIN AA6 [get_ports {segs1[7]}]
set_property PACKAGE_PIN T6 [get_ports {segs2[0]}]
set_property PACKAGE_PIN U5 [get_ports {segs2[1]}]
set_property PACKAGE_PIN U4 [get_ports {segs2[2]}]
set_property PACKAGE_PIN AB1 [get_ports {segs2[3]}]
set_property PACKAGE_PIN U7 [get_ports {segs2[4]}]
set_property PACKAGE_PIN AB4 [get_ports {segs2[5]}]
set_property PACKAGE_PIN V4 [get_ports {segs2[6]}]
set_property PACKAGE_PIN AA4 [get_ports {segs2[7]}]
set_property PACKAGE_PIN AB14 [get_ports {an[0]}]
set_property PACKAGE_PIN AA13 [get_ports {an[1]}]
set_property PACKAGE_PIN Y14 [get_ports {an[2]}]
set_property PACKAGE_PIN Y13 [get_ports {an[3]}]
set_property PACKAGE_PIN W13 [get_ports {an[4]}]
set_property PACKAGE_PIN V14 [get_ports {an[5]}]
set_property PACKAGE_PIN V13 [get_ports {an[6]}]
set_property PACKAGE_PIN U14 [get_ports {an[7]}]

set_property PACKAGE_PIN H17 [get_ports button_rst]

set_property PACKAGE_PIN AA18 [get_ports clk_100_]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLOCK/inst/clk_in1_pll]


set_property PACKAGE_PIN E21 [get_ports {switch_[11]}]

set_property PACKAGE_PIN C19 [get_ports btn]

set_property IOSTANDARD LVCMOS33 [get_ports btn]



set_property PACKAGE_PIN AB7 [get_ports {switch_[4]}]
set_property PACKAGE_PIN AA7 [get_ports {switch_[5]}]
set_property PACKAGE_PIN V7 [get_ports {switch_[6]}]
set_property PACKAGE_PIN Y6 [get_ports {switch_[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports out0]
set_property PACKAGE_PIN E20 [get_ports out0]


